### ISSUE TITLE
Guide to installation on Docker? Is there a stable/tested build for a specific Paddle image?

### ISSUE THREAD

**Issue by BrianZbr** [oliverfei/videocr-PaddleOCR#11]
I'm having a lot of trouble getting this working. I thought I'd have better luck in Docker, but at this point I've tried both `paddlepaddle/paddle:2.4.1` and `paddlepaddle/paddle:2.3.1` and in both cases after I install videocr-PaddleOCR, the paddle package can no longer be imported (`Illegal instruction (core dumped)`). It seems like videocr-PaddleOCR and paddle are fighting over the versions required for various packages.

Is there a there a stable version of videocr-PaddleOCR which is known to work with any specific paddle Docker image?

**Comment by oliverfei** [comment]
Does the Google Colab work for you? I have not tried installing on Docker yet.

The latest version of videocr-PaddleOCR should work with paddlepaddle 2.3.x

**Comment by BrianZbr** [comment]
Thank!, I'd overlooked the notebook link until you mentioned it here. It might be worth highlighting that more and briefly explaining what it is in the README.

The notebook does work for me, but I'd have to figure out if I can stop it from timing out long enough to process a significant chunk of video. At least now that I know it works in a specific environment I can access, I might work on getting it set up in Docker. 

I'll leave this issue open if you want to assign it to me? I'll make a PR if I have suggested updated to the README.

**Comment by oliverfei** [comment]
what language are you working with? PaddleOCR has worked pretty well for me for English and Chinese.
If you are using the colab notebook defaults, you'll probably want to adjust the crop window
