### ISSUE TITLE
[REQ] Online G-Colab version

### ISSUE THREAD

**Issue by forart** [oliverfei/videocr-PaddleOCR#4]
Hi there, this software is very interesting.

We wanna suggest you to build a Google-Colab notebook version in order to let users to try it online.

Check out (and, whly not, ask for help/collaboration) those other interesting virtual notebooks:
- [MiXLab](https://github.com/shirooo39/MiXLab) by @shirooo39;
- [Codemaster](https://github.com/mohitjoshi155/Codemaster) by @mohitjoshi155

Hope that inspires !

**Comment by oliverfei** [comment]
Hello, this has been added

**Comment by forart** [comment]
Thanks a lot for your work !

**Comment by oliverfei** [comment]
Google Colab's UI seems to have its own file upload interface so I just added a screenshot and a form where you can specify the input parameters

**Comment by forart** [comment]
> Google Colab's UI seems to have its own file upload interface
>
True, but users may don't know WHERE to load files exactly.

Thanks anyway.
