### ISSUE TITLE
`paddlepaddle-gpu` seems not accessible

### ISSUE THREAD

**Issue by medikoo** [oliverfei/videocr-PaddleOCR#9]
I'm on macOS, and whenever I try `python3.8 -m pip install paddlepaddle-gpu` I get `Could not find a version that satisfies the requirement paddlepaddle-gpu (from versions: none)`

```
$ python3.8 -m pip install paddlepaddle-gpu
ERROR: Could not find a version that satisfies the requirement paddlepaddle-gpu (from versions: none)
ERROR: No matching distribution found for paddlepaddle-gpu
``

I've searched the web and didn't find compelling solution to that problem

**Comment by oliverfei** [comment]
Have you tried installing from the baidu mirror mentioned in the PaddleOCR installation instructions here: https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/doc/doc_en/quickstart_en.md?

I will update the README
